[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.psram = enable
board_build.psram_mode = opi
monitor_speed = 115200

lib_deps =
    mathieucarbou/ESP Async WebServer@^3.0.6
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit INA219@^1.2.1
    adafruit/Adafruit BusIO@^1.16.1
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
    adafruit/RTClib@^2.1.4
